name: Deploy Airflow DAGs

on:
  push:
    branches:
      - main

jobs:
  deploy_airflow:
    runs-on: self-hosted

    steps:
      - name: Garantir que o repositório está atualizado
        run: |
          echo "==== Atualizando repositório maloka-dags ===="
          BASE_DIR=/home/admin
          DAG_REPO_DIR=$BASE_DIR/maloka-dags

          mkdir -p $DAG_REPO_DIR

          if [ ! -d "$DAG_REPO_DIR/.git" ]; then
            echo "Clonando repositório..."
            git clone https://github.com/maloka-ai/maloka-dags.git $DAG_REPO_DIR
          else
            echo "Repositório já existe. Atualizando..."
            cd $DAG_REPO_DIR
            git fetch --all
            git reset --hard origin/main
          fi

      - name: Copiar pastas para Airflow
        run: |
          echo "==== Copiando DAGs e configurações para o Airflow ===="
          AIRFLOW_DIR=/opt/airflow
          DAG_REPO_DIR=/home/admin/maloka-dags

          sudo mkdir -p $AIRFLOW_DIR

          copy_if_exists() {
            local src=$1
            local dest=$2
            if [ -d "$src" ]; then
              echo "Copiando $src para $dest..."
              sudo mkdir -p "$dest"
              sudo cp -a "$src/." "$dest/"
            else
              echo "Diretório $src não existe, pulando..."
            fi
          }

          copy_if_exists "$DAG_REPO_DIR/config" "$AIRFLOW_DIR/config"
          copy_if_exists "$DAG_REPO_DIR/dags" "$AIRFLOW_DIR/dags"
          copy_if_exists "$DAG_REPO_DIR/utils" "$AIRFLOW_DIR/utils"

      - name: Finalização
        run: |
          echo "==== Deploy finalizado com sucesso! ===="
          echo "Pastas no Airflow:"
          ls -la /opt/airflow
