name: Deploy Airflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Garantir que o c칩digo est치 atualizado
        run: |
          # Diret칩rio do runner no home do usu치rio
          BASE_DIR=/home/admin
          DAGS_DIR=$BASE_DIR/maloka-dags

          mkdir -p $DAGS_DIR

          if [ ! -d "$DAGS_DIR/.git" ]; then
            git clone https://github.com/maloka-ai/maloka-dags.git $DAGS_DIR
          else
            cd $DAGS_DIR
            git fetch --all
            git reset --hard origin/main
          fi

      - name: Copiar pastas para Airflow
        run: |
          AIRFLOW_DIR=/home/admin/airflow
          mkdir -p $AIRFLOW_DIR
          
          cp -r /home/admin/maloka-dags/config $AIRFLOW_DIR/
          cp -r /home/admin/maloka-dags/dags $AIRFLOW_DIR/
          cp -r /home/admin/maloka-dags/utils $AIRFLOW_DIR/
