name: Deploy Airflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: maloka-dags-runner
    steps:
      - name: Garantir que o código está atualizado
        run: |
          cd /opt
          # Se a pasta não existir, clona; se existir, faz reset
          if [ ! -d ".git" ]; then
            git clone https://github.com/maloka-ai/maloka-dags.git .
          else
            git fetch --all
            git reset --hard origin/main
          fi

      - name: Copiar pastas para Airflow
        run: |
          cp -r /opt/config /opt/airflow/
          cp -r /opt/dags /opt/airflow/
          cp -r /opt/utils /opt/airflow/
