name: Deploy Airflow DAGs to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy DAGs e dependências via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy das DAGs e instalação de libs via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1) Vá para o diretório raiz do Airflow
            cd /home/ubuntu/airflow/dags

            # 2) Atualize a branch main
            git fetch origin main
            git reset --hard origin/main

            # 3) Ative o virtualenv do Airflow
            cd /home/ubuntu/
            source airflow-venv/bin/activate

            # 4) Atualize pip e instale as dependências
            pip install --upgrade pip
            pip install -r requirements.txt

            # 5) (Opcional) Reinicie os serviços do Airflow
            pkill -f "airflow webserver" || true
            airflow webserver --port 8080 --daemon
            pkill -f "airflow scheduler" || true
            airflow scheduler --daemon
