name: Deploy Airflow DAGs to EC2

on:
  push:
    branches:
      - main   # agora usa a branch "main"

jobs:
  deploy:
    name: Deploy DAGs via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy das DAGs via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navega até o diretório de DAGs
            cd /home/ubuntu/airflow/dags

            # Sincroniza com a branch main
            git fetch origin main
            git reset --hard origin/main